name: Django CI

# Execute the workflow with every push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Env variables to execute the Pipeline without failure
      SECRET_KEY: v7m3c=uj%^uq^atc&brlv@8c420!9f_+=)@m(#-tka!@*#pogv
      DEBUG: true
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
